### PR TITLE
Sentor devel

### PR DESCRIPTION
**Pull request by adambinch**
DO NOT MERGE (WIP): Sentor can now call services, publish to topic and (rospy) sleep. See commit messages below.
TO DO: get it to execute shell commands, send toponav goals with a simple action server and log messages.

### CODE REVIEW

**Comment by adambinch** [comment]
The config `config/call.yaml` that I have been using to test teleports the robot in gazebo when it reaches WayPoint1 back to x=0,y=0. Then sentor sleeps for 3 seconds before relocalising the robot.

To replicate this test you need the RASberry repo and you need the following in your .rasberyrc
export ROBOT_NAME="thorvald_023"
export SCENARIO_NAME="sim_riseholme-uv_poly_act"

Then in terminal:
'cd $(rospack find rasberry_bringup)/tmule && tmule -c rasberry-simple_robot_corner_hokuyos.yaml -W 3 launch'

You should get thorvald in the riseholme gazebo world. Then run sentor:
`roslaunch sentor sentor.launch'

Then send the robot to WayPoint1

**Comment by adambinch** [comment]
They are backwards compatible. The new top level args (`execute` and `lock_exec`) in the config are optional. However i can still include version keys if that is good practice?

**Comment by marc-hanheide** [comment]
If we ensure backward compatibility then it's not needed for now

**Comment by francescodelduchetto** [comment]
I tried the proposed modifications with our Lindsey config and it doesn't seem to break anything. It looks good to me!

**Comment by adambinch** [comment]
@francescodelduchetto @marc-hanheide @Jailander @Michael Hutchinson I have finished adding what I wanted to add. Instructions for running sentor with the new features (see `execute.yaml`) are given in the updated README.md.

**Comment by adambinch** [comment]
Will update the README.md to document these latest changes on Monday.

**Comment by adambinch** [comment]
I cant see why this isnt building ...

**Comment by marc-hanheide** [comment]
I think it's just a problem of the melodic system being a bit unstable still. Ignore

**Comment by adambinch** [comment]
That is my last planned commit. Think its ready for field testing now.

**Pull request merged**
