### PR TITLE
Updated package xml and cmakelists.

### PR DESCRIPTION
**Pull request by adambinch**
Simplified topic map msg.
Some minor improvements.

### CODE REVIEW

**Comment by adambinch** [comment]
@marc-hanheide @francescodelduchetto i thought i would update the package xml with some missing dependencies, but `rosthrottle` does not have a kinetic release. Should we make a kinetic-devel branch?

**Comment by marc-hanheide** [comment]
I don't know rosthrottle, what does it do? There is throttle also in topic_tools package, does it not do the same thing? It's more standard and available in all distros.

**Comment by adambinch** [comment]
> I don't know rosthrottle, what does it do? There is throttle also in topic_tools package, does it not do the same thing? It's more standard and available in all distros.

rosthrottle allows you to make a throttled version of the topic in your python code. I did this for the topic mapping, for when you are mapping a topic with a high pub rate. You can set the rate in the topic map config (see `sentor/config/map.yaml`). With topic tools you would have to run a message throttle separately in the terminal or a launch file, which isn't very convenient. But I can remove this functionality if needs be.

**Comment by adambinch** [comment]
https://github.com/LCAS/sentor/blob/5fa6fd66e93f8199b1710c683ff78e4fb47d4024/src/sentor/TopicMapper.py#L164-L175

**Comment by francescodelduchetto** [comment]
From what I could see there is no python functionality in kinetic for throttling. 

I think we can make a kinetic-devel branch if there is nothing else against. Does that mean the throttling would need to be implemented in kinetic-devel in a different way, or we should leave it without?

**Comment by adambinch** [comment]
> From what I could see there is no python functionality in kinetic for throttling.
> 
> I think we can make a kinetic-devel branch if there is nothing else against. Does that mean the throttling would need to be implemented in kinetic-devel in a different way, or we should leave it without?

Would leave kinetic devel without i think. Kinetic devel users could use topic tools to throttle topics separately, at the command line.

**Comment by marc-hanheide** [comment]
I'd try to avoid separate branches as much as by all means possible, to be honest. 

I have just looked at the implementation of that RosThrottle package... It just launches `topic_tools/throttle` as an actual process with `popen`! So, really I would argue we should just use `topic_tools/throttle` directly.

**Comment by adambinch** [comment]
> I'd try to avoid separate branches as much as by all means possible, to be honest.
> 
> I have just looked at the implementation of that RosThrottle package... It just launches `topic_tools/throttle` as an actual process with `popen` (see https://github.com/UTNuclearRoboticsPublic/rosthrottle/blob/96ceb94f8f7aa067f8ac4a7fdf37022dc98602cd/src/rosthrottle/throttle.py#L115-L125)! So, really I would argue we should just use `topic_tools/throttle` directly.

lol ok i can just do what they did :)

**Pull request merged**
