### PR TITLE
Sentor can now map topic values.

### PR DESCRIPTION
**Pull request by adambinch**
A numpy array is created as a discretized representation of the metric map.
When a topic message is obtained, a user defined argument on the message is evaluated.
A weighted mean of this value is stored in an element of the array, where the indices of the element is
given by the 'map to baselink' tf transform. As more data from a location is gathered, the weighted mean
(and thus the 'topic map'), is updated. Any region of this topic map that
has not been explored will contain nans.

An extra top-level arg in the sentor config has been added for making topic maps. See `config/map.yaml`. 

Topic maps are broadcast onto the topic `/sentor/maps`

### CODE REVIEW

**Comment by adambinch** [comment]
To do : make a service for saving the maps, and optionally plot maps in real time.

**Comment by marc-hanheide** [comment]
Excuse my ignorance, but what is this for?

**Comment by adambinch** [comment]
It will allow us to record topic values according to where the robot is in the map. For example the error reported by the GPS, or difference between the GPS and MEL positions, or row detection failure. Then we would know where there are problems and we could then take steps to do something about it in those areas.

**Comment by Jailander** [comment]
@marc-hanheide sorry we didn't tell you about this, we have this crazy plan of using sentor's topic monitoring capabilities to also map variables around the environment which could be very useful for diagnostics in our case, so for example as @adambinch  mention's we can see GPS signal quality across the field, or see if the row detector is failing in some specific places. And I thought it could be very useful and cool for environmental monitoring tasks. 

What do you think?

**Comment by marc-hanheide** [comment]
Good idea, no objections

**Comment by adambinch** [comment]
@marc-hanheide @Jailander @MikHut 

Sentor topic map showing the probability of row detection failure in the simulation (generated as the robot does row traversal in each polytunnel). Resolution is 1.5 m^2.

Screenshot from 2020-03-03 15-55-43

**Comment by MikHut** [comment]
Awesome - so many possibilities!

**Comment by Jailander** [comment]
Amazing!!!
bitmoji

**Comment by marc-hanheide** [comment]
super cool! read to merge? And... is it backwards compatible, i.e., does @francescodelduchetto approve?

**Comment by adambinch** [comment]
@marc-hanheide i am pretty sure it is backwards compatible, but just to make sure it would be a good idea if @francescodelduchetto checks the lindsey config again (sorry Francesco)

**Comment by adambinch** [comment]
DO NOT MERGE YET - realtime plotting with matplotlib breaks when using more than one thread. Going to fix by plotting the topic maps outside of the threads (in the sentor node).

**Comment by adambinch** [comment]
@marc-hanheide would a confirmation that the lindsey config works in simulation be enough for merging this PR?

**Comment by Jailander** [comment]
@adambinch maybe you need to remove the WIP tag ;)

**Comment by adambinch** [comment]
> @adambinch maybe you need to remove the WIP tag ;)

Done

**Pull request merged**
